#!/bin/bash
set -e

# Fix chrome-sandbox permissions
if [ -f /opt/cxl-qvp/chrome-sandbox ]; then
    chown root:root /opt/cxl-qvp/chrome-sandbox
    chmod 4755 /opt/cxl-qvp/chrome-sandbox
fi

# Create symbolic link in /usr/local/bin
ln -sf /opt/cxl-qvp/cxl-qvp /usr/local/bin/cxl-qvp

# Update desktop database
if [ -x /usr/bin/update-desktop-database ]; then
    /usr/bin/update-desktop-database -q
fi
