#!/bin/bash
set -e

# Remove symbolic link from /usr/local/bin
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    rm -f /usr/local/bin/cxl-qvp
fi

# Update desktop database
if [ -x /usr/bin/update-desktop-database ]; then
    /usr/bin/update-desktop-database -q
fi
